### ISSUE TITLE
Applying latest changes [Derpy Hooves]

### ISSUE THREAD

**Issue by Karill** [wieschoo/BotSuite#15]
All changes made since the last update from me need to be added to the product.

Since i have not only changed my own files but many others aswell it would be good if we could speak about the process of merging the (now) very far apart versions.
If interisted what my version looks like: https://bitbucket.org/KarillEndusa/botsuite.net

**Comment by Karill** [comment]
Since active development stopped in this repository i don't really see why i should now even try to merge the two versions to here.

**Comment by ViRb3** [comment]
I am still here and interested in bringing everything together, though I cannot promise to be active a lot due to school and studies.

**Comment by wieschoo** [comment]
@Karill I do not use Bitbucket for several reasons and I will not link to the bitbucket repo on the botsuite.net page. I appended your project history to this project.
