### ISSUE TITLE
How to can I use botsuite?

### ISSUE THREAD

**Issue by neverbackdown** [wieschoo/BotSuite#20]
Dear wieschoo,

I don't know using botsuite without tutorial. I found this tutorial but image don't show:( . Here is the link:

http://www.codebot.de/index.php/Thread/9852-SimCitySocial-Harvester-mit-der-wieschoo-BotSuite/
http://www.codebot.de/index.php/Thread/9870-Playforia-Gems-mit-der-wieschoo-BotSuite-2-1-1/
http://www.codebot.de/index.php/Thread/9952-Ikariam-in-C-auslesen/

Please tell me how to can I use it. 

Thank you so much.

**Comment by ViRb3** [comment]
It really depends on what you want to do.
If you have any specific questions feel free to ask them here :)

**Comment by wieschoo** [comment]
The images were hosted by myself. I do not have any interest to do babysitting for the website anymore. You can write me an email.
